export default{
  orderNumber:['订单号'],
  customer:['客户名称'],
  contactWay:['联系方式'],
  reserveTime:['订单时间'],
  // beginTime:['开始时间'],
  // endTime:['结束时间'],
  unsubscribeTime:['退订时间'],
  mode:['消费模式','',{}],
  // modeName:['消费模式'],
  // orderType:['订单类型','',{mapper:{1:'消费',2:'充值',3:'退订'}}],
  room:['预订包间'],
  session:['预定场次'],
  prop:['预订性质'],
  unsubscribeProp:['退订性质'],
  orderPerson:['预订人'],
  orderAmount:['订单金额'],
  deposit:['押金'],
  cuisine:['菜品'],
  balanceOffset:['余额抵消'],
  IntegralOffset:['积分抵消'],
  // actualCharge:['实收金额'],
  // payWay:['支付方式','',{mapper:{1:'现金',2:'微信',3:'支付宝',4:'信用卡',5:'储蓄卡'}}],
  weChartCollection:['微信收款'],
  alipayCollection:['支付宝收款','',{minWidth:90}],
  CreditCardCollection:['信用卡收款','',{minWidth:90}],
  DebitCardCollection:['储蓄卡收款','',{minWidth:90}],
  cash:['现金收款'],
  // deduct:['提成'],
}