export default{
  orderNumber:['订单号'],
  customer:['客户名称'],
  contactWay:['联系方式'],
  reserveTime:['预订时间'],
  beginTime:['开始时间'],
  endTime:['结束时间'],
  mode:['消费模式','',{}],
  // modeName:['消费模式'],
  // orderType:['订单类型','',{mapper:{1:'消费',2:'充值',3:'退订'}}],
  consumptionType:['消费类型'],
  consumptionTypeName:['消费类型'],
  room:['预订包间'],
  session:['预定场次'],
  prop:['预订性质'],
  orderPerson:['预订人'],
  originalPrice:['订单原价格'],
  actualConsumption:['实际消费额','',{minWidth:90}],
  activeCoupon:['活动优惠金额'],
  cashierCoupon:['收银优惠金额'], 
  given:['赠送金额'],
  balanceOffset:['余额抵消'],
  IntegralOffset:['积分抵消'],
  actualCharge:['实收金额'],
  // // payWay:['支付方式','',{mapper:{1:'现金',2:'微信',3:'支付宝',4:'信用卡',5:'储蓄卡'}}],
  // weChartCollection:['微信收款'],
  // alipayCollection:['支付宝收款','',{minWidth:90}],
  // CreditCardCollection:['信用卡收款','',{minWidth:90}],
  // DebitCardCollection:['储蓄卡收款','',{minWidth:90}],
  // cash:['现金收款'],
  deduct:['提成总额'],
}